### ISSUE TITLE
Can the virtual machines on the local area network be connected to the network like the 0.6 version

### ISSUE THREAD

**Issue by TOPPOOL** [CESSProject/cess-bucket#173]
Can the virtual machines on the local area network be connected to the network like the 0.6 version

能否像0.6版本一样能够让 本机的局域网的虚拟机也能够连上网络
![微信截图_20230831225621](https://github.com/CESSProject/cess-bucket/assets/97819498/d360f344-f949-47c6-9206-82214d68807f)

**Comment by AstaFrode** [comment]
@TOPPOOL Storage nodes have always been configured with public IP addresses, otherwise you will not be able to store service files and thus be unable to obtain higher profits. Please refer to our manual requirements: https://app.gitbook.com/o/kiTNX10jBU59sjnYZbiH /s/QzzR05bLvPP615saNCGf/storage-miner#mining-preparation
