### ISSUE TITLE
Consensus node configuration issues

### ISSUE THREAD

**Issue by Nedvl** [CESSProject/cess-bucket#225]
Hello team,

I am trying to configure a consensus node. following this tutorial (https://docs.cess.cloud/core/consensus-miner/running). Everything goes smoothly up until I try to generate the session key.
When typing the command "cess tools rotate-keys" I get "null"  as an output. I have tried many times and checked everything more than once.  Asked questions in the discord channel and presented info there but no one was able to help so far. 
The next screenshots are after I did "cess down"; "cess purge"; "cess config set";  "cess start" and "cess tools rotate-keys".

![Screenshot 2024-01-16 191504](https://github.com/CESSProject/cess-bucket/assets/156853122/f7c1ba3f-3efa-4ce1-98ae-e232c1f7fbcb)

![Screenshot 2024-01-16 233422](https://github.com/CESSProject/cess-bucket/assets/156853122/9d4cbcd2-ecf4-44ff-9128-47e819268fe9)

![Screenshot 2024-01-16 233648](https://github.com/CESSProject/cess-bucket/assets/156853122/2c165ff3-58ee-4e22-a0e5-f66ae4a15f80)

Can someone help?

**Comment by 0xbillw** [comment]
We are very sorry for replying to you so late!
This issue is actually related to the [cess-nodeadm](https://github.com/CESSProject/cess-nodeadm) program. And it's probably the version of the program that matters.
Can you provide the output of the `cess version` command?
Make sure your output is consistent with the following:

```shell
Node mode: authority
Profile: testnet
nodeadm version: v0.5.2
Docker images:
  config-gen: config-gen 1.4.8 53976b848715
  chain: cess-node 0.7.5-unknown 6cc28c2aa3a2
  kld-agent: kaleido-rotator 0.3.1-testnet 092b9de72bce
  kld-sgx: kaleido 0.3.1-testnet d8d1864d56d7
```

If inconsistent, please download[ v1.5.2](https://github.com/CESSProject/cess-nodeadm/releases/tag/v0.5.2) version to reinstall and configure again.

Thank you so much for your feedback!
Please continue to leave a message if you have any questions.

**Comment by Nedvl** [comment]
Thank you for the answer.
This is the output of cess version:
![image](https://github.com/CESSProject/cess-bucket/assets/156853122/cc4af937-9c3c-4a54-bc64-0b6ef3d381c7)
Indeed there is a difference in the nodeadm version although I have installed the latest version as mentioned in the manual I will download v0.5.2  and try again.
